### ISSUE TITLE
Colour inside the brush to match zoom window

### ISSUE THREAD

**Issue by PhilGrunewald** [PhilGrunewald/yourdata#1]
to make it clear for users that the lower graph shows the extent of the brush window above,
- all of the top graph should be dimmed with exception of the 'selected' brush extent
- the region should have the same colour as the bottom (zoom) graph

optional extra:
- two thin lines could be drawn from the left and right corners of the brush to the left and right edges of the zoom graph

**Comment by MarinaDiakonova** [comment]
Done
