### ISSUE TITLE
Zoom lines from brush to Zoom graph

### ISSUE THREAD

**Issue by MarinaDiakonova** [PhilGrunewald/yourdata#3]

**Comment by MarinaDiakonova** [comment]
Done and pushed (upstream?)

**Comment by PhilGrunewald** [comment]
Hi Marina,
This is to say: well done for going home and thank you for the lines ;-)

(And also to test if we can message each other using github...)

All the best,
Phil


On Thu, Dec 08, 2016 at 05:54:59AM -0800, MarinaDiakonova wrote:
Done and pushed (upstream?)
